MoviePlatform/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('review.urls', namespace='review')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

review/urls.py
from django.urls import path
from . import views
from .views import (
    MovieListView,
    ReviewListView,
    ReviewDetailView,
    MovieCreateView,
    GenreCreateView,
    ReviewerListView,
    ReviewerDetailView,
    MovieDetailView,
    CreateReviewView,
    AllGenresView,
    GenreMoviesView, ReviewDeleteView,
)

app_name = 'review'

urlpatterns = [
    path('', views.index, name='index'),
    path('genres/', AllGenresView.as_view(),
         name='all_genres'),
    path('genres/<int:pk>/',
         GenreMoviesView.as_view(), name='all-genre-movies'),
    path('genres/create/', GenreCreateView.as_view(), name='genre-create'),
    path('movies/', MovieListView.as_view(), name='movies-list'),
    path('movies/<int:movie_id>/',
         MovieDetailView.as_view(), name='movie-detail'),
    path('movies/create/', MovieCreateView.as_view(), name='movie-create'),
    path('reviews/',
         ReviewListView.as_view(), name='reviews-list'),
    path('reviews/<int:pk>/',
         ReviewDetailView.as_view(), name='review-detail'),
    path('reviews/create/',
         CreateReviewView.as_view(), name='create-review'),
    path('write_review/<int:movie_id>/',
         views.CreateReviewView.as_view(), name='write_review'),
    path('reviews/<int:pk>/delete/',
         ReviewDeleteView.as_view(), name='review-delete'),
    path('reviewers/',
         ReviewerListView.as_view(), name='reviewers-list'),
    path('reviewers/<int:pk>/',
         ReviewerDetailView.as_view(), name='reviewer-detail'),
]

templates/includes/navigation.html
{% load i18n static theme_material_kit %}

<div class="container position-sticky z-index-sticky top-0">
  <div class="row">
    <div class="col-12">
      <nav
          class="navbar navbar-expand-lg  blur border-radius-xl top-0 mt-4 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
        <div class="container-fluid px-0">
          <a class="navbar-brand font-weight-bolder ms-sm-3" href="/"
             rel="tooltip" title="" data-placement="bottom">
            Home
          </a>
          <a class="navbar-brand font-weight-bolder ms-sm-3" href="{% url "review:movies-list" %}"
             rel="tooltip" title="" data-placement="bottom">
            Movies
          </a>
          <a class="navbar-brand font-weight-bolder ms-sm-3" href="{% url "review:all_genres" %}"
             rel="tooltip" title="" data-placement="bottom">
            Genres
          </a>
          <a class="navbar-brand font-weight-bolder ms-sm-3" href="{% url "review:reviews-list" %}"
             rel="tooltip" title="" data-placement="bottom">
            Reviews
          </a>
        <a class="navbar-brand font-weight-bolder ms-sm-3" href="{% url "review:reviewers-list" %}"
             rel="tooltip" title="" data-placement="bottom">
            Reviewers
          </a>
          {% if not request.user.is_authenticated %}
            <a class="btn btn-outline-success my-2 my-sm-0" href="{% url "login" %}"
               rel="tooltip" title="" data-placement="bottom">
              Login
            </a>
          {% else %}
            <a class="navbar-brand font-weight-bolder ms-sm-3" href="{% url "review:reviewer-detail" pk=user.id %}"
               rel="tooltip" title="" data-placement="bottom">
              My cabinet
            </a>
            <form method="post" action="{% url 'logout' %}">
              {% csrf_token %}
              <button class="btn btn-outline-danger my-2 my-sm-0" type="submit">logout</button>
            </form>
          {% endif %}
        </div>
      </nav>
    </div>
  </div>
</div>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Previous</span>
        </a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <span class="page-link" aria-disabled="true">&laquo;</span>
      </li>
    {% endif %}

    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="page-item active">
          <span class="page-link">{{ i }}</span>
        </li>
      {% else %}
        <li class="page-item">
          <a href="?{% query_transform request page=i %}" class="page-link">{{ i }}</a>
        </li>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Next</span>
        </a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <span class="page-link" aria-disabled="true">&raquo;</span>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
    <li class="list-group-item">User: <a href="{{ user.get_absolute_url }}">{{ user.get_username }}</a></li>
    <li class="list-group-item">
      <form method="post" action="{% url 'logout' %}">
        {% csrf_token %}
        <button class="link-button" type="submit">Logout</button>
      </form>
    </li>
  {% else %}
    <li class="list-group-item"><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
  {% endif %}

  <br>

  <li class="list-group-item"><a href="{% url 'review:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'review:movies-list' %}">Movies</a></li>
  <li class="list-group-item"><a href="{% url 'review:reviews-list' %}">Reviews</a></li>
  <li class="list-group-item"><a href="{% url 'review:all_genres' %}">Genres</a></li>
  <li class="list-group-item"><a href="{% url "review:reviewers-list" %}">Reviewers</a></li>#}
</ul>