MoviePlatform/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('review.urls', namespace='review')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

review/urls.py
from django.urls import path
from . import views
from .views import (
    MovieListView,
    ReviewListView,
    ReviewDetailView,
    MovieCreateView,
    GenreCreateView,
    ReviewerListView,
    ReviewerDetailView,
    MovieDetailView,
    CreateReviewView,
    AllGenresView,
    GenreMoviesView, ReviewDeleteView,
)

app_name = 'review'

urlpatterns = [
    path('', views.index, name='index'),
    path('genres/', AllGenresView.as_view(),
         name='all_genres'),
    path('genres/<int:pk>/',
         GenreMoviesView.as_view(), name='all-genre-movies'),
    path('genres/create/', GenreCreateView.as_view(), name='genre-create'),
    path('movies/', MovieListView.as_view(), name='movies-list'),
    path('movies/<int:movie_id>/',
         MovieDetailView.as_view(), name='movie-detail'),
    path('movies/create/', MovieCreateView.as_view(), name='movie-create'),
    path('reviews/',
         ReviewListView.as_view(), name='reviews-list'),
    path('reviews/<int:pk>/',
         ReviewDetailView.as_view(), name='review-detail'),
    path('reviews/create/',
         CreateReviewView.as_view(), name='create-review'),
    path('write_review/<int:movie_id>/',
         views.CreateReviewView.as_view(), name='write_review'),
    path('reviews/<int:pk>/delete/',
         ReviewDeleteView.as_view(), name='review-delete'),
    path('reviewers/',
         ReviewerListView.as_view(), name='reviewers-list'),
    path('reviewers/<int:pk>/',
         ReviewerDetailView.as_view(), name='reviewer-detail'),
]

review/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.http import HttpResponse
from django.urls import reverse


class Genre(models.Model):
    name = models.CharField(max_length=100, unique=True)

    class Meta:
        ordering = ['name']

    def __str__(self: models) -> str:
        return self.name


class Reviewer(AbstractUser):
    favourite_movies = models.ManyToManyField(
        'Movie', related_name='favourite_movies')

    def __str__(self: models) -> str:
        return self.username


class Movie(models.Model):
    title = models.CharField(max_length=255, unique=True)
    description = models.TextField(blank=True, null=True)
    genre = models.ManyToManyField(Genre)
    release_year = models.IntegerField()
    reviewers = models.ManyToManyField(
        Reviewer, through='Review', related_name='reviewed_movies'
    )

    class Meta:
        ordering = (
            'title',
            'release_year',
        )

    def __str__(self: models) -> str:
        return self.title

    def get_absolute_url(self: models) -> HttpResponse:
        return reverse('review:movie-detail', args=[str(self.id)])


class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE,
                             related_name='review_author')
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE,
                              related_name='movie_reviews')
    RATING_CHOICES = [
        (0, '0 - Terrible'),
        (1, '1 - Poor'),
        (2, '2 - Fair'),
        (3, '3 - Good'),
        (4, '4 - Very Good'),
        (5, '5 - Excellent'),
    ]
    rating = models.IntegerField(choices=RATING_CHOICES)
    review_text = models.TextField()
    added_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-rating']

    def __str__(self: models) -> str:
        return f'{self.user} - {self.movie.title}'

review/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import QuerySet
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic, View
from django.views.generic import DetailView, ListView, DeleteView

from .forms import (
    MovieCreateForm,
    GenreForm,
    ReviewForm,
    MovieSearchForm,
    GenreSearchForm,
    ReviewSearchForm,
)
from .models import Movie, Review, Genre, Reviewer


def index(request: HttpRequest) -> HttpResponse:

    num_movies = Movie.objects.count()
    num_genres = Genre.objects.count()
    num_reviews = Review.objects.count()
    num_reviewers = Reviewer.objects.count()

    context = {
        'num_movies': num_movies,
        'num_genres': num_genres,
        'num_reviews': num_reviews,
        'num_reviewers': num_reviewers,
    }

    return render(request, 'review/index.html', context=context)


class AllGenresView(ListView):
    model = Genre
    template_name = 'review/all_genres.html'
    context_object_name = 'genres'
    paginate_by = 5

    def get_queryset(self: View) -> QuerySet:
        queryset = super().get_queryset()
        form = GenreSearchForm(self.request.GET)
        if form.is_valid():
            query = form.cleaned_data.get('query')
            if query:
                queryset = queryset.filter(name__icontains=query)
        return queryset

    def get_context_data(self: View, **kwargs: None) -> dict:
        context = super().get_context_data(**kwargs)
        context['search_form'] = GenreSearchForm(self.request.GET)
        return context


class GenreMoviesView(DetailView):
    model = Genre
    template_name = 'review/movies_by_genre.html'
    context_object_name = 'genre'

    def get_context_data(self: View, **kwargs: None) -> [str]:
        context = super().get_context_data(**kwargs)
        genre = self.get_object()
        context['movies'] = Movie.objects.filter(genre=genre)
        return context


class GenreCreateView(LoginRequiredMixin, generic.CreateView):
    model = Genre
    form_class = GenreForm
    success_url = reverse_lazy('review:all_genres')


class MovieCreateView(LoginRequiredMixin, generic.CreateView):
    model = Movie
    form_class = MovieCreateForm
    success_url = reverse_lazy('review:movies-list')

    def form_valid(self: model, form: MovieCreateForm) -> HttpResponse:
        movie = form.save(commit=False)
        movie.save()
        genres = form.cleaned_data.get('genres')
        movie.genre.add(*genres)
        return super().form_valid(form)

    def get_form_kwargs(self: None) -> dict:
        kwargs = super().get_form_kwargs()
        genre_id = self.request.GET.get('genre_id')
        if genre_id:
            kwargs['initial'] = {'genres': [genre_id]}  # Preselect genre
        return kwargs


class MovieListView(generic.ListView):
    model = Movie
    queryset = Movie.objects.prefetch_related('genre')
    template_name = 'review/movies_list.html'
    context_object_name = 'movies_list'
    paginate_by = 5

    def get_context_data(self: None,
                         *, object_list: None = None,
                         **kwargs: None) -> dict:
        context = super(MovieListView, self).get_context_data(**kwargs)
        title = self.request.GET.get('title', '')
        context['search_form'] = MovieSearchForm(initial={'title': title})
        return context

    def get_queryset(self: None) -> QuerySet:
        queryset = Movie.objects.prefetch_related('genre')
        form = MovieSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(title__icontains=form.cleaned_data['title'])
        return queryset


class ReviewListView(LoginRequiredMixin, ListView):
    model = Review
    template_name = 'review/reviews_list.html'
    context_object_name = 'reviews_list'
    paginate_by = 5

    def get_queryset(self: None) -> QuerySet:
        queryset = super().get_queryset()
        title = self.request.GET.get('query')
        if title:
            queryset = queryset.filter(movie__title__icontains=title)
        return queryset

    def get_context_data(self: None, **kwargs: None) -> None:
        context = super().get_context_data(**kwargs)
        context['form'] = ReviewSearchForm(self.request.GET)
        return context


class ReviewDetailView(LoginRequiredMixin, DetailView):
    model = Review


class CreateReviewView(LoginRequiredMixin, View):
    def get_initial_data(self: View, movie_id: int) -> None | dict:
        if movie_id:
            movie = get_object_or_404(Movie, pk=movie_id)
            return {'movie': movie}
        return None

    def get(self: View,
            request: HttpRequest, movie_id: int = None) -> HttpResponse:
        initial_data = self.get_initial_data(movie_id)
        form = ReviewForm(initial=initial_data)
        return render(request, 'review/review_form.html', {'form': form})

    def post(self: View,
             request: HttpRequest, movie_id: int = None) -> HttpResponse:
        initial_data = self.get_initial_data(movie_id)
        form = ReviewForm(request.POST, initial=initial_data)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.save()
            return redirect('review:reviews-list')
        return render(request, 'review/review_form.html', {'form': form})


class ReviewerListView(LoginRequiredMixin, ListView):
    model = Reviewer
    template_name = 'review/reviewers_list.html'
    context_object_name = 'reviewer_list'
    paginate_by = 5


class ReviewerDetailView(LoginRequiredMixin, DetailView):
    model = Reviewer
    template_name = 'review/reviewers_detail.html'
    context_object_name = 'reviewer'


class ReviewDeleteView(LoginRequiredMixin, DeleteView):
    model = Review
    success_url = reverse_lazy('review:reviews-list')

    def get_queryset(self: View) -> QuerySet:
        return super().get_queryset().filter(user=self.request.user)


class MovieDetailView(LoginRequiredMixin, DetailView):
    def get(self: View,
            request: HttpRequest, movie_id: int = None) -> HttpResponse:
        movie = get_object_or_404(Movie, pk=movie_id)
        user = request.user
        is_favorite = movie in user.favourite_movies.all()
        context = {
            'movie': movie,
            'is_favorite': is_favorite,
        }
        return render(request, 'review/movie_detail.html', context)

    def post(self: View,
             request: HttpRequest, movie_id: int = None) -> HttpResponse:
        movie = get_object_or_404(Movie, pk=movie_id)
        user = request.user

        if 'add_to_favorites' in request.POST:
            user.favourite_movies.add(movie)
        elif 'remove_from_favorites' in request.POST:
            user.favourite_movies.remove(movie)
        return redirect('review:movie-detail', movie_id=movie_id)

templates/review/all_genres.html
{% extends 'layouts/base_background.html' %}
{% load crispy_forms_filters %}
{% load static %}

{% block title %} All Genres {% endblock title %}
{% block body %} class="blog-author bg-gray-200" {% endblock body %}

{% block header %}
  {% include 'includes/navigation.html' %}
{% endblock header %}

{% block content %}
  <header>
    <div class="page-header min-height-400" style="background-image: url('{% static 'img/360_F_562252610_Watb1rsYXzmDnCDqxA2CFEsS72o8D05E.jpg' %}');" loading="lazy">
      <span class="mask bg-gradient-dark opacity-8"></span>
    </div>
  </header>

  <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6 mb-4">
    <section class="py-3">
      <div class="container">
        <a href="{% url 'review:genre-create' %}" class="btn btn-primary link-to-page float-end">
          Add a new genre
        </a>
        <div class="row justify-content-center">
          <div class="col-md-8">
            <div class="d-flex justify-content-between align-items-center mb-3">
              <form action="" method="get" class="form-inline" data-width="auto">
                <input type="text" name="query" class="form-control mb-2 mr-sm-2" placeholder="Search genres by name">
                <button class="btn btn-primary" type="submit">Search 🔍</button>
              </form>
            </div>

            <div class="genres-container">
              <h1 class="text-center mb-4">All Genres</h1>
              <ul>
                {% for genre in genres %}
                  <li class="genre-item">
                    <a href="{% url 'review:all-genre-movies' genre.id %}" class="genre-link">{{ genre.name }}</a>
                  </li>
                {% empty %}
                  <li>No genres found</li>
                {% endfor %}
              </ul>
              {% include "includes/pagination.html" %}
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
{% endblock content %}

templates/review/genre_form.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Add genre</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
<br>
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/review/index.html
{% extends 'layouts/base_background.html' %}
{% load static %}

{% block title %}Critiquill{% endblock title %}

{% block body %} class="index-page bg-gray-200" {% endblock body %}

{% block content %}

  <header class="header-2">
    <div class="page-header min-vh-75 relative" style="background-image: url('{% static 'img/360_F_562252610_Watb1rsYXzmDnCDqxA2CFEsS72o8D05E.jpg' %}')">
      <span class="mask bg-gradient-primary opacity-3"></span>
      <div class="container">
        <div class="row">
          <div class="col-lg-7 text-center mx-auto">
            <h1 class="text-white pt-3 mt-n5">Welcome to CritiQuill</h1>
            <p class="lead text-white mt-3">
              CritiQuill is open for you if you love movies and even more if you like to express your feelings about them.    
            </p>
          </div>
        </div>
      </div>
    </div>
  </header>

  <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6">

    <section class="pt-3 pb-4" id="count-stats">
      <div class="container">
        <div class="row">
          <div class="col-lg-9 mx-auto py-3">
            <div class="row">
              <div class="col-md-4 position-relative">
                <div class="p-3 text-center">
                  <h1 class="text-gradient text-primary">{{ num_movies }}</h1>
                  <h5 class="mt-3">Movies</h5>
                  <p class="text-sm font-weight-normal">All you already knew and more</p>
                </div>
                <hr class="vertical dark">
              </div>
              <div class="col-md-4 position-relative">
                <div class="p-3 text-center">
                  <h1 class="text-gradient text-primary">{{ num_genres }}</h1>
                  <h5 class="mt-3">Genres</h5>
                  <p class="text-sm font-weight-normal">From little laughs to nightmare fuel</p>
                </div>
                <hr class="vertical dark">
              </div>
              <div class="col-md-4">
                <div class="p-3 text-center">
                  <h1 class="text-gradient text-primary">{{ num_reviews }}</h1>
                  <h5 class="mt-3">Reviews</h5>
                  <p class="text-sm font-weight-normal">Tell us what you think</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
{% endblock %}
{% block footer %}
{% endblock %}

templates/review/movie_detail.html
{% extends 'layouts/base_background.html' %}
{% load crispy_forms_filters %}
{% load static %}

{% block title %} {{ movie.title }} {% endblock title %}
{% block body %} class="blog-author bg-gray-200" {% endblock body %}

{% block header %}
  {% include 'includes/navigation.html' %}
{% endblock header %}

{% block content %}
  <header>
    <div class="page-header min-height-400" style="background-image: url('{% static 'img/pexels-suzy-hazelwood-3886870.jpg' %}');"
         loading="lazy">
      <span class="mask bg-gradient-dark opacity-8"></span>
    </div>
  </header>
  <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6 mb-4">
    <section class="py-3">
      <div class="container">
        <div class="row">
          <div class="col-lg-6">
            <h3 class="mb-5">Movie Details</h3>
          </div>
        </div>
        <div class="row">
          <div class="col-md-8">
            <div class="movie-details">
              <h1>Title: {{ movie.title }}</h1>
              <hr>
              <p><strong>Description:</strong> {{ movie.description }}</p>
              <p><strong>Genres:</strong>
                {% if movie.genre.all %}
                  {% for genre in movie.genre.all %}
                    {{ genre.name }}{% if not forloop.last %}, {% endif %}
                  {% endfor %}
                {% else %}
                  No genres specified
                {% endif %}
              </p>
              <p><strong>Release year:</strong> {{ movie.release_year }}</p>
              <hr>

              <h2>Reviews:</h2>
{% if movie.movie_reviews.all %}
  <ul class="review-list">
    {% for review in movie.movie_reviews.all %}
      <li class="review-item">
        <a href="{% url 'review:review-detail' review.id %}" class="review-link" title="Read full review">{{ review.user }} rated this movie {{ review.get_rating_display }}</a>
      </li>
    {% endfor %}
  </ul>
{% else %}
  <p>No reviews yet.</p>
{% endif %} 

              <a href="{% url 'review:write_review' movie.id %}" class="btn btn-primary">Write a review about this movie</a>

              <br><br>

              {% if request.user.is_authenticated %}
                {% if is_favorite %}
                  <form action="{% url 'review:movie-detail' movie.id %}" method="post" style="display: inline;">
                    {% csrf_token %}
                    <button type="submit" name="remove_from_favorites" class="btn btn-danger" style="border: none;">Remove from Favorites</button>
                  </form>
                {% else %}
                  <form action="{% url 'review:movie-detail' movie.id %}" method="post" style="display: inline;">
                    {% csrf_token %}
                    <button type="submit" name="add_to_favorites" class="btn btn-success" style="border: none;">Add to Favorites</button>
                  </form>
                {% endif %}
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>

{% endblock content %}

templates/review/movies_by_genre.html
{% extends "layouts/base.html" %}

{% block content %}
<div class="movies-by-genre">
  <h1>{{ genre.name }} Movies</h1>
  {% if movies %}
    <ul>
      {% for movie in movies %}
        <li class="movie-item">
          <a href="{% url 'review:movie-detail' movie.id %}" class="movie-link">{{ movie.title }}</a> - <span class="release-year">{{ movie.release_year }}</span>
        </li>
      {% endfor %}
    </ul>
    <a href="{% url 'review:movie-create' %}?genre_id={{ genre.id }}" class="btn btn-primary">Add another {{ genre.name }} Movie</a>
  {% else %}
    <p>No {{ genre.name }} movies so far. Be the first to add one.</p>
    <a href="{% url 'review:movie-create' %}?genre_id={{ genre.id }}" class="btn btn-primary">Add a {{ genre.name }} Movie</a>
  {% endif %}
</div>
{% endblock %}

templates/review/movies_list.html
{% extends 'layouts/base_background.html' %}
{% load crispy_forms_filters %}
{% load static %}

{% block title %} All Movies {% endblock title %}
{% block body %} class="blog-author bg-gray-200" {% endblock body %}

{% block header %}
  {% include 'includes/navigation.html' %}
{% endblock header %}

{% block content %}
  <header>
    <div class="page-header min-height-400" style="background-image: url('{% static 'img/360_F_562252610_Watb1rsYXzmDnCDqxA2CFEsS72o8D05E.jpg' %}');" loading="lazy">
      <span class="mask bg-gradient-dark opacity-8"></span>
    </div>
  </header>

  <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6 mb-4">
    <section class="py-3">
      <a href="{% url 'review:movie-create' %}" class="btn btn-primary link-to-page float-end">
        Add a new movie
      </a>
      <div class="container">
        <div class="row">
          <div class="col-lg-6">
            <h3 class="mb-5">Check our movie base</h3>
          </div>
        </div>

        <form action="" method="get" class="form-inline" data-width="auto">
          <input type="text" name="title" class="form-control mb-2 mr-sm-2" placeholder="Search movies by title">
          <input class="btn btn-primary" type="submit" value="Search 🔍">
        </form>
        <br>
        <div class="table-responsive"> <!-- Add this class to make the table responsive -->
          <table class="table">
            <thead>
              <tr>
                <th>Title</th>
                <th>Genres</th>
                <th>Release Year</th>
              </tr>
            </thead>
            <tbody>
              {% for movie in movies_list %}
              <tr>
                <td><a href="{% url 'review:movie-detail' movie_id=movie.id %}">{{ movie.title }}</a></td>
                <td>
                  {% if movie.genre.all %}
                    {{ movie.genre.all|join:', ' }}
                  {% else %}
                    No genres listed
                  {% endif %}
                </td>
                <td>{{ movie.release_year }}</td>
              </tr>
              {% empty %}
              <tr>
                <td colspan="3">There are no movies</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        {% include "includes/pagination.html" %}
      </div>
    </section>
  </div>
{% endblock content %}

templates/review/review_detail.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block content %}
  
  <div class="container mt-4">
    <div class="row">
      <div class="col-md-8">
        <div class="card">
          <div class="card-body">
            <h1 class="card-title">Author: {{ review.user.username }}</h1>
            <hr>
            <p class="card-text"><strong>Movie: {{ review.movie.title }}</strong></p>
            <hr>
            <p class="card-text"><strong>Review:
              <br>              
              {{ review.review_text }}</strong></p>
            <hr>
            <p class="card-text"><strong>Added:
              <br>
              {{ review.added_at }}</strong></p>
          </div>
          {% if request.user == review.user %}
          <div class="card-footer">
            <form action="{% url 'review:review-delete' review.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger">Delete Review</button>
            </form>
          </div>
          {% endif %}
        </div>
      </div>
      <div class="col-md-4">        
      </div>
    </div>
  </div>

{% endblock %}

templates/review/review_form.html
{% extends 'layouts/base_background.html' %}
{% load crispy_forms_filters %}
{% load static %}

{% block title %} Write review {% endblock title %}
{% block body %} class="blog-author bg-gray-200" {% endblock body %}

{% block header %}
  {% include 'includes/navigation.html' %}
{% endblock header %}

{% block content %}
  <header>
    <div class="page-header min-height-400" style="background-image: url('{% static 'img/360_F_562252610_Watb1rsYXzmDnCDqxA2CFEsS72o8D05E.jpg' %}');"
         loading="lazy">
      <span class="mask bg-gradient-dark opacity-8"></span>
    </div>
  </header>
  <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6 mb-4">
    <section class="py-3">
      <div class="container">
        <div class="row">
          <h1>Write review</h1>
          <hr>
          <form action="" method="post" novalidate>
            {% csrf_token %}
            {{ form|crispy }}
            <style>
              #id_movie,
              #id_rating {
                border: 1px solid #ced4da;
                border-radius: 4px;
                padding: 8px;
                width: 100%;
              }
            </style>
            <br>
            <input type="submit" value="Submit" class="btn btn-primary">
          </form>
        </div>
      </div>
    </section>
  </div>
{% endblock content %}

templates/review/reviewers_detail.html
{% extends "layouts/base.html" %}

{% block content %}
<div class="container mt-5">
  <div class="reviewer-details">
    <h1 class="mb-4">Reviewer: {{ reviewer.username }}</h1>
    <hr>

    <h2 class="mb-3">Favourite Movies:</h2>
    {% if reviewer.favourite_movies.all %}
      <ul class="list-group mb-4">
        {% for movie in reviewer.favourite_movies.all %}
          <li class="list-group-item">
            <a href="{% url 'review:movie-detail' movie.id %}" class="movie-link" title="View movie details">{{ movie.title }}</a>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p>No favourite movies specified.</p>
    {% endif %}

    <h2 class="mb-3">Reviews:</h2>
    {% if reviewer.review_author.all %}
      <ul class="list-group mb-4">
        {% for review in reviewer.review_author.all %}
          <li class="list-group-item">
            <a href="{% url 'review:review-detail' pk=review.id %}" class="review-link" title="View review details">{{ review.movie.title }} ({{ review.rating }} stars)</a>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p>No reviews found for this reviewer.</p>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/review/reviewers_list.html
{% extends 'layouts/base_background.html' %}
{% load crispy_forms_filters %}
{% load static %}

{% block title %}All Reviewers {% endblock title %}
{% block body %} class="blog-author bg-gray-200" {% endblock body %}

{% block header %}
  {% include 'includes/navigation.html' %}
{% endblock header %}

{% block content %}
  <header>
    <div class="page-header min-height-400" style="background-image: url('{% static 'img/360_F_562252610_Watb1rsYXzmDnCDqxA2CFEsS72o8D05E.jpg' %}');" loading="lazy">
      <span class="mask bg-gradient-dark opacity-8"></span>
    </div>
  </header>

  <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6 mb-4">
    <section class="py-3">     
      <div class="container">
        <div class="row">
          <div class="col-lg-6">
            <h3 class="mb-5">All Reviewers</h3>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <table class="table">
              <thead>
                <tr>
                  <th>Reviewer</th>
                  <th>Favourite Movies</th>
                </tr>
              </thead>
              <tbody>
                {% for reviewer in reviewer_list %}
                  <tr>
                    <td><a href="{% url 'review:reviewer-detail' pk=reviewer.pk %}" class="text-decoration-none">{{ reviewer.username }}</a></td>
                    <td>
                      {% if reviewer.favourite_movies.count > 0 %}
                        {% for movie in reviewer.favourite_movies.all|slice:":2" %}
                          {{ movie.title }}
                          {% if not forloop.last %}, {% endif %}
                        {% endfor %}
                        {% if reviewer.favourite_movies.count > 2 %}
                          , ...
                        {% endif %}
                      {% else %}
                        No favourite movies
                      {% endif %}
                    </td>
                  </tr>
                {% empty %}
                  <tr>
                    <td colspan="2">There are no reviewers.</td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
        {% include "includes/pagination.html" %}
      </div>
    </section>
  </div>
{% endblock content %}

templates/review/reviews_list.html
{% extends 'layouts/base_background.html' %}
{% load crispy_forms_filters %}
{% load static %}

{% block title %} All reviews {% endblock title %}
{% block body %} class="blog-author bg-gray-200" {% endblock body %}

{% block header %}
  {% include 'includes/navigation.html' %}
{% endblock header %}

{% block content %}
  <header>
    <div class="page-header min-height-400" style="background-image: url('{% static 'img/360_F_562252610_Watb1rsYXzmDnCDqxA2CFEsS72o8D05E.jpg' %}');" loading="lazy">
      <span class="mask bg-gradient-dark opacity-8"></span>
    </div>
  </header>

  <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6 mb-4">
    <section class="py-3">
      <a href="{% url 'review:create-review' %}" class="btn btn-primary link-to-page float-end">
        Write your Review
      </a>
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <h3 class="mb-5">All Reviews </h3>
          </div>
        </div>

        <form action="" method="get" class="form-inline" data-width="auto">
          <input type="text" name="query" class="form-control mb-2 mr-sm-2" placeholder="Search reviews">
          <input class="btn btn-primary" type="submit" value="Search 🔍">
        </form>
        <br>
        <div class="row">
          <div class="col-md-12">
            <table class="table">
              <thead>
                <tr>
                  <th>Reviewed By</th>
                  <th>Rating</th>
                  <th>Movie Title</th>
                  <th>Review</th>
                </tr>
              </thead>
              <tbody>
                {% for review in reviews_list %}
                <tr>
                  <td class="reviewer-name">{{ review.user }}</td>
                  <td class="rating">{{ review.rating }} stars</td>
                  <td>
                    <a href="{% url 'review:movie-detail' movie_id=review.movie.id %}" class="movie-title">
                      {{ review.movie.title }}
                    </a>
                  </td>
                  <td>
                    <a href="{% url 'review:review-detail' pk=review.id %}" class="review-detail">
                      "{{ review.review_text|truncatechars:30 }}"...
                    </a>
                  </td>
                </tr>
                {% empty %}
                <tr>
                  <td colspan="4">There are no reviews.</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            {% include "includes/pagination.html" %} <!-- Pagination -->
          </div>
        </div>
      </div>
    </section>
  </div>
{% endblock content %}